import Link from "next/link";
import { Header } from "@/components/Header";

const features=[
  ["Résumé clair","Le courrier est traduit en français simple."],
  ["Échéances détectées","Les dates importantes sont extraites automatiquement."],
  ["Réponse prête","Une réponse personnalisable est préparée."],
  ["Checklist d'actions","Vous savez exactement quoi faire et dans quel ordre."],
  ["Sources officielles","Les démarches utiles renvoient vers les bons organismes."],
  ["Rappels","Ne manquez plus une date importante."]
];

export default function Home(){return <><Header/><main><section className="container hero"><div><span className="eyebrow">Assistant administratif IA</span><h1>Comprenez vos courriers. Agissez sans stress.</h1><p>Prenez une photo ou importez un PDF. En moins de 30 secondes, obtenez un résumé, les actions à réaliser, les échéances et une réponse prête.</p><div className="actions"><Link className="btn primary" href="/analyse">Analyser un courrier</Link><Link className="btn" href="/dashboard">Voir le tableau de bord</Link></div><p style={{fontSize:14}}>Essai gratuit · Sans carte bancaire · Vous gardez toujours le contrôle</p></div><div className="mock"><div className="card urgent"><small>COURRIER DÉTECTÉ</small><h3>Direction générale des Finances publiques</h3><p>Déclaration à transmettre avant le 18 août.</p></div><div className="status" style={{marginTop:14}}><div className="stat"><span>Urgence</span><strong>Élevée</strong></div><div className="stat"><span>Temps estimé</span><strong>6 min</strong></div></div><div className="card" style={{marginTop:14}}><h3>Actions à réaliser</h3><p>✓ Vérifier les informations</p><p>✓ Joindre l'avis demandé</p><p>✓ Envoyer la réponse préparée</p></div></div></section><section id="fonctionnalites" className="container section"><h2>Tout ce qu'il faut pour terminer la démarche</h2><p className="lead">Pas seulement comprendre : agir, suivre et classer.</p><div className="grid">{features.map(([t,d])=><div className="card" key={t}><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="container section"><div className="mock"><h2>Tout est sous contrôle.</h2><div className="status"><div className="stat"><span>Urgences</span><strong>1</strong></div><div className="stat"><span>Actions cette semaine</span><strong>3</strong></div><div className="stat"><span>Dossiers terminés</span><strong>17</strong></div></div></div></section><section className="container section"><h2>Commencez gratuitement</h2><p className="lead">Analysez vos premiers courriers sans carte bancaire.</p><Link className="btn primary" href="/analyse">Essayer maintenant</Link></section></main><footer className="footer"><div className="container">© 2026 Courrier Facile · Mentions légales · Confidentialité · CGU</div></footer></>}
